### ISSUE TITLE
Release Build .mxe64 crashing Max on Windows

### ISSUE THREAD

**Issue by mhamilt** [NullMember/MaxFirmata#1]
The [latest release](https://github.com/NullMember/MaxFirmata/releases/tag/v2.0.2) of the `mxe64` crashing windows on instantiation.

Building from source there is no issue and `maxfirmata` works as expected.

Tested on multiple Windows 10 (and Windows 11) machines.

**Comment by NullMember** [comment]
Thanks for your issue. I think binaries are not working due mingw (it's always pain to build dynamic library with it). I've switched to MSVC and published new [release](https://github.com/NullMember/MaxFirmata/releases/tag/v2.0.3). I hope it will work. Please let me know if you encounter any issue.

**Comment by mhamilt** [comment]
I can confirm this is working for me.

**Comment by NullMember** [comment]
> I can confirm this is working for me.

Thanks for confirmation
