### ISSUE TITLE
Maxfirmata on new MacBook Pro (2021 - Apple M1)

### ISSUE THREAD

**Issue by nani42** [NullMember/MaxFirmata#2]
Hi there!
I keep getting the following error message when creating a new [maxfirmata] object in Max 8: "maxfirmata: could not load due to incorrect architecture". The object itself gets autofilled when I type in the word "maxfirmata" and all the help files and documentation are there but the object itself always stays yellow and doesn't work.
I'm using one of the new MacBook Pros that came out this autumn with the Apple M1 Max chip. Could this issue be due to incompatibility with my chip?
Thanks!

**Comment by NullMember** [comment]
Current OSX maxfirmata objects support only AMD64 architecture. I try to compile it for OSX ARM64 today. I will ping you when it's available.

**Comment by NullMember** [comment]
@nani42 I've released [new version](https://github.com/NullMember/MaxFirmata/releases/tag/v2.0.4) with ARM64 support. Can you check?

**Comment by nani42** [comment]
Brilliant - I'll check now!

**Comment by nani42** [comment]
I can confirm that this works now - so the issue can be closed! Thank you!

**Comment by NullMember** [comment]
Thanks for confirmation. You're welcome.
